spring.application.name=operation-system

# =====================
# SERVER
# =====================
server.port=${PORT:8080}

# =====================
# DATABASE (RENDER POSTGRESQL)
# =====================
spring.datasource.url=jdbc:postgresql://dpg-d7p137dckfvc73800mo0-a:5432/operation_icil
spring.datasource.username=operation_icil_user
spring.datasource.password=eqyyzeyf9MMkwBxa5q9P3AdG9AAy9l8M
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect