spring.application.name=froms

# PORT
server.port=${PORT:8080}

# =====================
# DATABASE (USE ENV VARIABLES ONLY)
# =====================
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# USIWEKE dialect manually (Hibernate 6 inajua yenyewe)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =====================
# LOGGING
# =====================
logging.level.com.zaxxer.hikari=DEBUG

# =====================
# DISABLE H2
# =====================
spring.h2.console.enabled=false
