spring.application.name=froms

# PORT
server.port=${PORT:8080}

# =====================
# DATABASE (FIX KUBWA IPO HAPA)
# =====================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# IMPORTANT (weka hii ili ku-force Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =====================
# LOGGING (DEBUG DB)
# =====================
logging.level.com.zaxxer.hikari=DEBUG

# =====================
# DISABLE H2
# =====================
spring.h2.console.enabled=false