package com.daniphord.mahanga.Config;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DatabaseStartupCheckTest {

    private final DatabaseStartupCheck databaseStartupCheck = new DatabaseStartupCheck();

    @Test
    void repairLegacyVideoSessionSchemaAddsMissingAudioColumnAndBackfillsRows() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:legacy-video-schema;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table video_sessions (
                        id bigint generated by default as identity primary key,
                        start_time timestamp not null,
                        status varchar(255),
                        participant_type varchar(255)
                    )
                    """);
            statement.execute("""
                    insert into video_sessions (start_time, status, participant_type)
                    values (CURRENT_TIMESTAMP, 'LIVE', 'OFFICER')
                    """);
        }

        databaseStartupCheck.repairLegacyVideoSessionSchema(dataSource);

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            try (ResultSet columns = connection.getMetaData().getColumns(null, null, "VIDEO_SESSIONS", "AUDIO_ENABLED")) {
                assertTrue(columns.next());
            }
            try (ResultSet resultSet = statement.executeQuery("select count(*) from video_sessions where audio_enabled = true")) {
                assertTrue(resultSet.next());
                assertEquals(1, resultSet.getInt(1));
            }
        }
    }
}
